name: Laravel CI/CD

on:
  push:
    branches:
      - main # Set your default branch here
  pull_request:
    branches:
      - main # Set your default branch here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Set your PHP version here
        extensions: mbstring, bcmath, sqlite3

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --no-dev --optimize-autoloader

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run tests
      run: php artisan test --env=testing

    - name: Cache configuration
      run: php artisan config:cache

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && git pull origin main && composer install --no-dev && php artisan migrate --force"
