name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /path/to/your/app
            docker-compose down
            docker-compose pull
            docker-compose up -d --build

            docker-compose exec db sh -c "exec mysql -u root -p secret -e \"GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY secret; FLUSH PRIVILEGES;\""


            docker cp ./database.sql mysql:/database.sql


            docker-compose exec db sh -c "exec mysql -u root -p secret digitalnesttest < /database.sql"

